
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 */
public class movietic extends javax.swing.JFrame {

    /**
     * Creates new form movietic
     */
    public movietic() {
        initComponents();
    }

    
    DefaultTableModel model = new DefaultTableModel();
    Connection con;
    PreparedStatement ps1;
    PreparedStatement ps2;

    movietic(int i) {
        initComponents();
        deletemovie(i);
    }

    movietic(String movie, int i) {
        initComponents();
        addmovie(movie);
    }
    
  
    
    /**
     * 
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chk11 = new javax.swing.JCheckBox();
        chk22 = new javax.swing.JCheckBox();
        chk33 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtqty = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtcombo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtsub = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtbal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOVIE BOOKING");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 0, 310, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 0, 102));
        jButton5.setText("LOGIN AS ADMIN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chk1.setForeground(new java.awt.Color(255, 255, 255));
        chk1.setText("MORNING");
        jPanel2.add(chk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        chk2.setForeground(new java.awt.Color(255, 255, 255));
        chk2.setText("EVENING");
        jPanel2.add(chk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        chk3.setForeground(new java.awt.Color(255, 255, 255));
        chk3.setText("NIGHT");
        chk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk3ActionPerformed(evt);
            }
        });
        jPanel2.add(chk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TICKET TYPE");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SLOT");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        chk11.setForeground(new java.awt.Color(255, 255, 255));
        chk11.setText("ODC");
        jPanel2.add(chk11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        chk22.setForeground(new java.awt.Color(255, 255, 255));
        chk22.setText("BALCONY");
        jPanel2.add(chk22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        chk33.setForeground(new java.awt.Color(255, 255, 255));
        chk33.setText("CORNER");
        jPanel2.add(chk33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QUANTITY");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 70, 30));
        jPanel2.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 40, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select Movie");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 130, 30));

        txtcombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conjuring(Horror)", "Annihilation(sci-fi)", "Undisputed(Action)" }));
        txtcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomboActionPerformed(evt);
            }
        });
        jPanel2.add(txtcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 150, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 102));
        jButton4.setText("REMOVE");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 80, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("ADD");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 550, 210));

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TICKET TYPE", "SLOT", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 530, 220));

        txtsub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsub.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubActionPerformed(evt);
            }
        });
        getContentPane().add(txtsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subtotal");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pay");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 40, 30));

        txtpay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 100, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("Invoice");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 100, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Balance");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 60, 30));

        txtbal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtbal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtbal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 100, 30));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, 10));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\sohail\\Downloads\\photo-1536440136628-849c177e76a1.jfif")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 40, 1020, 590));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk3ActionPerformed
    
    public int corner = 0;
    public int balcony = 0;
    public int normal = 0;
    public String slot;
    public String tickettype;
    public int price;
    public int quantity;
    public int total;
    public int sum = 0;
    public String movie;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        if(chk1.isSelected())
        {   
            price = 500;
            slot = "Morning";
            
            if(chk11.isSelected()){
                if(normal != 50){
                normal++;    
                price = price ;
                tickettype = "Normal";
            }}
            if(chk22.isSelected()){
                if(balcony != 10){
                balcony++;    
                price = price + 50;
                tickettype = "Balcony";
            }}
            if(chk33.isSelected()){
                if(corner != 10){
                corner++;
                price=price+100;
                tickettype = "Corner";
            }}
        }
         if(chk2.isSelected()){
            price = 700;
            slot = "Evening";
            if(chk11.isSelected()){
                if(normal != 50){
                normal++;
                price = price ;
                tickettype = "normal";
            }}
            if(chk22.isSelected()){
                if(balcony != 10){
                balcony++;    
                price = price + 50;
                tickettype = "Balcony";
            }}
            if(chk33.isSelected()){
                if(corner != 10){
                corner++;    
                price=price+100;
                tickettype = "Corner";
            }}
        }
         if(chk3.isSelected()){
            price = 900;
            slot = "Night";
            if(chk11.isSelected()){
                 if(normal != 50){
                normal++;
                price = price ;
                tickettype = "normal";
            }}
            if(chk22.isSelected()){
                if(balcony!=10){
                balcony++;
                price = price + 50;
                tickettype = "Balcony";
            }}
            if(chk33.isSelected()){
                if(corner!=10){
                corner++;
                price=price+100;
                tickettype = "Corner";
            }}
        }
        
        quantity = Integer.parseInt(txtqty.getValue().toString());
        total = price * quantity;
        
        if (quantity >= 1 && price >= 1){
        model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{
            tickettype,
            slot,
            price,
            quantity,
            total
            
        });
        
         for(int i = 0; i<jTable1.getRowCount();i++){
             sum = sum + Integer.parseInt(jTable1.getValueAt(i, 4).toString());
         }     
        txtsub.setText(String.valueOf(sum));
        
        movie = (String) txtcombo.getSelectedItem();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select complete details");
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubActionPerformed

    public void sales(){
        
       String subtotal = txtsub.getText();
       String pay = txtpay.getText();
       String bal = txtbal.getText();
    if(Integer.parseInt(txtpay.getText())>= Integer.parseInt(txtsub.getText()))
    {    
       int lastid = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","ahmer1234");
            String query = "insert into sales(subtotal,pay,balance)values(?,?,?)";
            ps1 = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
            
            ps1.setString(1, subtotal);
            ps1.setString(2, pay);
            ps1.setString(3, bal);
            ps1.executeUpdate();
            
            ResultSet rs = ps1.getGeneratedKeys();
            
            if(rs.next()){
                lastid = rs.getInt(1);
            }
            
            
            int rowss = jTable1.getRowCount();
            
            String query1 = "insert into sales_product(sales_id,slot,tickettype,qty,price,total)values(?,?,?,?,?,?)";
            ps2 = con.prepareStatement(query1);
            
            String tickettype = "";
            String slot = "";
            int price;
            int qty;
            int total;
            
            
            
            for (int i =0 ; i <jTable1.getRowCount();i++){
             
                tickettype = (String)jTable1.getValueAt(i, 0);
                slot =(String)jTable1.getValueAt(i, 1);
                price =(int)jTable1.getValueAt(i, 2);
                qty =(int)jTable1.getValueAt(i, 3);
                total=(int)jTable1.getValueAt(i, 4);
                
                
                ps2.setInt(1, lastid);
                ps2.setString(2, slot);
                ps2.setString(3, tickettype);
                ps2.setInt(4, qty);
                ps2.setInt(5, price);
                ps2.setInt(6, total);
                
                ps2.executeUpdate();
                
                }
            
          //  new ticket(movie,slot,tickettype,quantity,subtotal,lastid).setVisible(true);
            new report(movie,slot,tickettype,quantity,subtotal,lastid).setVisible(true);
            JOptionPane.showMessageDialog(this, "Sales Complete");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(movietic.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(movietic.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }
    else{
        JOptionPane.showMessageDialog(this, "Insufficient amount");
            
    }
    }
    public void deletemovie(int i){
      
      txtcombo.removeItemAt(i);
      
    }
    public void addmovie(String movie){
        txtcombo.addItem(movie);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        
        int sub = Integer.parseInt(txtsub.getText());
        int pay = Integer.parseInt(txtpay.getText());
        int balance = pay - sub;
        txtbal.setText(String.valueOf(balance));
        
        
        sales();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomboActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        model.removeRow(jTable1.getSelectedRow());
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movietic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movietic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movietic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movietic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movietic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk11;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk22;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk33;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtbal;
    private javax.swing.JComboBox<String> txtcombo;
    private javax.swing.JTextField txtpay;
    private javax.swing.JSpinner txtqty;
    private javax.swing.JTextField txtsub;
    // End of variables declaration//GEN-END:variables
}
